---
# tasks file for mariadb
- name: install mariadb
  apt:
    name: 
      - mariadb-server
    state: present

- name: python db driver
  apt:
    name: python3-mysqldb
    state: latest

- name: start mariadb
  service:
    name: mysql
    state: started

- name: template my.cnf
  template:
    src: templates/my.cnf.j2
    dest: /root/.my.cnf

- name: change root password
  community.mysql.mysql_user:
    name: root
    password: "{{ db_password }}"

- name: create table
  community.mysql.mysql_db:
    check_implicit_admin: yes
    name: wordpress
    state: present
