---
# tasks file for wordpress
- name: install nginx
  apt:
    name: apache2
    state: present
  
- name: start nginx
  service:
    name: apache2
    state: started

- name: download wordpress
  get_url:
    url: "{{ wordpress_url }}"
    dest: /tmp/wordpress.tar.gz

- name: unarchive wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ wordpress_dest }}"
    remote_src: yes

- name: template wp-conf
  template:
    src: templates/wp-conf.php.j2
    dest: "{{ wordpress_dest }}wordpress/wp-config.php"

- name: restart nginx
  service:
    name: apache2
    state: restarted
