---
# tasks file for php
- name: install latest php
  apt:
    name:
      - php
      - php-mysql
    state: present

- name: set timezone
  community.general.ini_file:
    path: /etc/php.ini
    section: Date
    option: date.timezone
    value: '"Asia/Tokyo"'

- name: copy php info
  copy:
    src: "{{ role_path }}/files/phpinfo.php"
    dest: /var/www/html/phpinfo.php